### ISSUE TITLE
can not find codesystem for ValueSet-kbv-s-kbv-dmp.xml

### ISSUE THREAD

**Issue by beowulf2005** [hl7germany/basisprofil-de#187]
ValueSet-kbv-s-kbv-dmp.xml 
line 19-23
	&lt;compose&gt;
		&lt;include&gt;
			&lt;system value="http://fhir.de/CodeSystem/kbv/s-kbv-dmp"/&gt;
		&lt;/include&gt;
	&lt;/compose&gt;

But I can't find this CodeSystem with this canonical url in basisprofil-de-stu3.
The CodeSystem-kbv-s-kbv-dmp.xml in basisprofil-de-stu3 has 
canonical url=https://fhir.kbv.de/CodeSystem/74_CS_SFHIR_KBV_DMP

**Comment by lhitc** [comment]
Between the first releases of Basisprofile-de (based und FHIR STU3) and the current, FHIR R4 based releases of Basisprofil-de, KBV has started using FHIR and defining canonical URLs for the code systems they issue.
It is common understanding that the canonical URLs should be defined by the original issuer of a code system (in this case KBV for the KBV "Schlüsseltabellen").
Since KBV now has taken that responsibility, the previous names defined in Basis-DE up to release 0.2.x are deprecated.

**Comment by lhitc** [comment]
To further clarify in regard to the question, KBV has issued STU3 based canonical URLs (like the mentioned .../74_CS_SFHIR_KBV_DMP). These, all starting with "74_", have lived alongside the KBV related URLs defined under http://fhir.de for a short period of time.
For STU3 based specifications/implementation guides, they may still be in use / required to be used.
From FHIR R4 the harmonization mentioned above takes place.

**Comment by beowulf2005** [comment]
My request is: Can we fix the "ValueSet-kbv-s-kbv-dmp.xml".
to "include" the right canonical url "https://fhir.kbv.de/CodeSystem/74_CS_SFHIR_KBV_DMP"

like so: 
ValueSet-kbv-s-kbv-dmp.xml line 19-23

&lt;compose&gt;
&lt;include&gt;
&lt;system value="https://fhir.kbv.de/CodeSystem/74_CS_SFHIR_KBV_DMP"/&gt;
&lt;/include&gt;
&lt;/compose&gt;

**Comment by lhitc** [comment]
I now see that the problem seems to be that Basis-DE (STU3)  defines a CodeSystem "https://fhir.kbv.de/CodeSystem/74_CS_SFHIR_KBV_DMP" (which is wrong) but the ValueSet refers to "http://fhir.de/CodeSystem/kbv/s-kbv-dmp" (which is correct for Basis-DE (STU3) and even used by the KBV themselves in their specs.
So apparently the wrong name for the CodeSystem mistakenly made it into Basis-DE (STU3).

This is addressed in #184, so leaving this issue closed an re-opening #184
